#pragma once

enum app_event_t {
    APP_EVENT_STARTUP = 0,
    APP_EVENT_PROVISIONING_DONE,
    APP_EVENT_WIFI_CONNECTED,
    APP_EVENT_WIFI_FAILED,
    APP_EVENT_MQTT_CONNECTED,
    APP_EVENT_MQTT_FAILED,
    APP_EVENT_FACTORY_RESET,
    APP_EVENT_TIMEOUT
};
